spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  application:
    name: auth-service
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:mysql://user-db:3306/user_db
    username: root
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    loadbalancer:
      enabled: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: ${JWT_SECRET}
  exp: 3600000
  refresh:
    exp: 604800000

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30