server:
  port: 8080

spring:
  webflux:
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-next-service-instance: 2
        max-retries-on-same-service-instance: 1
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          filters:
            - name: AuthenticationFilter
              args: {}
          predicates:
            - Path=/api/auth/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - name: AuthenticationFilter
              args: {}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - name: AuthenticationFilter
              args: {}

        - id: file-storage-service
          uri: lb://file-storage-service
          predicates:
            - Path=/images/**
          filters:
            - RewritePath=/images/(?<segment>.*), /api/files/$\{segment}
  data:
    redis:
      host: redis
      port: 6379
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  exp: 3600000
  refresh:
    exp: 604800000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG