spring:
  application:
    name: payment-service
  stripe:
    secret: ${STRIPE_SECRET}
  webhook:
    secret: ${WEBHOOK_KEY}
  datasource:
    url: jdbc:mysql://payment-db:3306/payment_db
    username: root
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    loadbalancer:
      enabled: true
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 0

front:
  url: http://localhost:4200/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30