spring:
  application:
    name: product-service
  data:
    redis:
      host: redis-auth
      port: 6379
    mongodb:
      authentication-database: admin
      username: root
      password: root
      host: product-db
      port: 27017
      database: productDB
  cloud:
    loadbalancer:
      enabled: true
  kafka.bootstrap-servers: kafka:9092

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
